<?php

namespace Chdtu\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChdtuGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChdtuGroupRepository extends EntityRepository
{
}
