fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
chdtu_user:
    resource: "@ChdtuUserBundle/Resources/config/routing.yml"
chdtu_main:
    resource: "@ChdtuMainBundle/Resources/config/routing.yml"
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
