<?php

namespace Chdtu\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubjectMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectMapRepository extends EntityRepository
{
    public function findAllRecords()
    {
        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT p, s.name FROM ChdtuMainBundle:SubjectMap p LEFT JOIN p.subject s'
            )
            ->getResult();
        echo '<pre>';
        var_dump($result);
        echo '</pre>';
        exit;

//
//        return
    }
}
